version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: vagas_user
      POSTGRES_PASSWORD: vagas_password
      POSTGRES_DB: vagas_db
    ports:
      - "5432:5432"
    volumes:
      - vagas_pgdata:/var/lib/postgresql/data

volumes:
  vagas_pgdata:
